# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
# limanskaya.c@gmail.com
name: Upload via ssh

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.16.2]

    steps:
      - uses: actions/checkout@master
      - name: copy file via ssh password
        uses: garygrossgarten/github-action-scp@release
        with:
          local: readme.md
          remote: public_html/readme.md
          host: ssh.stackcp.com
          username: convey.world
          password: ${{ secrets.PASSWORD }}
